dir .\boucheron >> dir_all.txt
dir .\buccellati >> dir_all.txt
dir .\bvlgari >> dir_all.txt
dir .\cartier >> dir_all.txt
dir .\chanel >> dir_all.txt
dir .\chaumet >> dir_all.txt
dir .\chopard >> dir_all.txt
dir .\dior >> dir_all.txt
dir .\fred >> dir_all.txt
dir .\harrywinston >> dir_all.txt
dir .\hermes >> dir_all.txt
dir .\louisvuitton >> dir_all.txt
dir .\marli >> dir_all.txt
dir .\messika >> dir_all.txt
dir .\pasquale >> dir_all.txt
dir .\piaget >> dir_all.txt
dir .\roberto >> dir_all.txt
dir .\tiffany >> dir_all.txt
dir .\vca >> dir_all.txt